### PR TITLE
Hebrew Translation 

### PR DESCRIPTION
**Pull request by thefourcraft**
## Description

This pull request adds a Hebrew translation.
The translation has been thoroughly reviewed and tested to ensure accuracy and completeness.

## Changes

- Added a new `he_IL.json` file in the `lang` directory containing the Hebrew translation.

## Benefits

This pull request allows players who speak Hebrew to enjoy the Nova plugin in their native language, improving their overall experience with the plugin.

## Testing

The translation has been tested in-game to ensure that it is accurate and complete.

### CODE REVIEW

**Comment by NichtStudioCode** [comment]
Hi, please use [weblate](https://translate.xenondevs.xyz) for translations.

**Comment by thefourcraft** [comment]
it doesn't work, I wanted to use it...

**Comment by ByteZ1337** [comment]
Doesn't seem like you have an account. You can only access the project pages after creating an account.

**Comment by thefourcraft** [comment]
yeah I see, need to authenticate with GitHub 
now I have access, but this translation is the same, I can update the website also :) give me a moment to `ctrl + c` and `ctrl + v`

**Pull request closed without merging**
